name: Run Tests on Pull Requests
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: macos-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
      - name: Run unit tests
        run: pytest --cov=my_project tests/
 
      - name: Fail if tests fail
        if: failure()
        run: |
          echo "Tests failed! PR cannot be merged."
          exit 1

Dispose d’un menu contextuel
