name: Run Tests in Docker

on: [push, pull_request]  # Exécuter les tests à chaque push et pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation d'Ubuntu car Docker est bien supporté

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fizzbuzz-app .

      - name: Run tests inside Docker container
        run: docker run --rm fizzbuzz-app
  
